# Generated by Django 5.2.7 on 2026-01-12 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_asistencia_id_alter_cargo_id_alter_empleado_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
